// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    var commentForm, getCommentText, render, textBox,
      _this = this;
    commentForm = $('#commentform');
    textBox = commentForm.find('textarea');
    getCommentText = function() {
      var input, _i, _len, _ref;
      _ref = commentForm.serializeArray();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        input = _ref[_i];
        if (input.name === 'comment') {
          return input.value;
        }
      }
    };
    render = function(htmlToPreview) {
      var comments, parent, text;
      if (_this.template == null) {
        comments = $('article.comment');
        _this.template = comments.first().clone();
        _this.template.find('.reply, #respond').remove();
        parent = textBox.parents('#respond').prev('.comment');
        if (!parent.is(':visible')) {
          parent = comments.last();
        }
        parent.after(_this.template);
      }
      if (!htmlToPreview.trim()) {
        return _this.template.remove() && delete _this.template;
      }
      text = _this.template.find('.comment-content');
      return text.html(htmlToPreview);
    };
    $('.comment-reply-link, .cancel-comment-reply-link').on('click', function() {
      return delete _this.template;
    });
    return textBox.on('keyup', _.throttle(function() {
      return $.post(window.gfm_preview.ajaxurl, {
        action: 'gfm_preview',
        gfm_text: getCommentText()
      }, function(response) {
        return render(response);
      });
    }, 200));
  });

}).call(this);
